import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#007650",
        "surface-container-highest": "#e1e3e4",
        "surface-tint": "#732ee4",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#e4e0f5",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "outline": "#7b7487",
        "on-primary": "#ffffff",
        "inverse-primary": "#d2bbff",
        "on-primary-container": "#ede0ff",
        "on-background": "#191c1d",
        "primary-fixed": "#eaddff",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#76ffc2",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#d2bbff",
        "surface-dim": "#d9dadb",
        "surface-container": "#edeeef",
        "primary-container": "#7c3aed",
        "secondary": "#5e5c6e",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#f8f9fa",
        "on-secondary-fixed-variant": "#464555",
        "on-secondary-container": "#646274",
        "on-primary-fixed": "#25005a",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed-dim": "#c7c4d8",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3132",
        "primary": "#630ed4",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#ccc3d8",
        "surface-container-low": "#f3f4f5",
        "on-error-container": "#93000a",
        "secondary-container": "#e4e0f5",
        "on-primary-fixed-variant": "#5a00c6",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#191c1d",
        "on-secondary-fixed": "#1b1a29",
        "on-surface-variant": "#4a4455",
        "tertiary": "#005b3d",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap-mobile": "64px",
        "unit": "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "32px",
        "section-gap-desktop": "120px"
      },
    },
  },
  plugins: [],
} satisfies Config;
