import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function NotFound() {
  return (
    <>
      <Navbar />
      <main className="pt-40 pb-24 text-center min-h-screen flex flex-col justify-center items-center px-margin-mobile">
        <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center text-primary mb-6">
          <span className="material-symbols-outlined text-[40px]">explore_off</span>
        </div>
        <h1 className="text-4xl font-bold text-on-surface mb-4" style={{ fontFamily: "var(--font-plus-jakarta-sans)" }}>
          Page Not Found
        </h1>
        <p className="text-on-surface-variant max-w-md mx-auto mb-8 font-body-md">
          The requested page is not active or hasn&apos;t been generated by the Kudu CMS engine yet.
        </p>
        <Link
          href="/"
          className="px-6 py-3 bg-primary text-on-primary rounded-full font-bold hover:opacity-90 shadow-md transition-all"
        >
          Return to Homepage
        </Link>
      </main>
      <Footer />
    </>
  );
}
